version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    day: "monday"
    time: "05:00"
    interval: "weekly"
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    day: "monday"
    time: "05:00"
    interval: "weekly"
  open-pull-requests-limit: 10
