# Field Types Configuration
# Defines available field types with their properties, categories, and source types

development: &development
  unicorn_birth_certificate:
    type: document_upload
    category: unicorn_identity
    subcategory: basic_documents
    source_type: authentic_source
    required_for: [supplies, works]
    optional_for: []
  unicorn_horn_measurement:
    type: text_field
    category: unicorn_identity
    subcategory: physical_characteristics
    source_type: authentic_source
    required_for: [services]
    optional_for: []
  pizza_allergy_declaration:
    type: checkbox_field
    category: pizza_exclusions
    subcategory: health_declarations
    source_type: honor_declaration
    required_for: [supplies]
    optional_for: []
  pineapple_pizza_stance:
    type: checkbox_field
    category: pizza_exclusions
    subcategory: preferences
    source_type: honor_declaration
    required_for: [services]
    optional_for: []
  coffee_addiction_level:
    type: text_field
    category: coffee_compliance
    subcategory: consumption_metrics
    source_type: authentic_source
    required_for: [supplies]
    optional_for: [works]
  croissant_eating_frequency:
    type: text_field
    category: coffee_compliance
    subcategory: consumption_metrics
    source_type: honor_declaration
    required_for: [works]
    optional_for: []
  rocket_piloting_license:
    type: document_upload
    category: rocket_certifications
    subcategory: licenses_and_permits
    source_type: authentic_source
    required_for: []
    optional_for: [supplies, works]
  moon_landing_experience:
    type: checkbox_field
    category: rocket_certifications
    subcategory: experience_records
    source_type: authentic_source
    required_for: []
    optional_for: [services]
  ninja_stealth_certificate:
    type: document_upload
    category: ninja_qualifications
    subcategory: professional_certifications
    source_type: authentic_source
    required_for: [works]
    optional_for: [supplies]
    defense_required: true
  invisible_skill_proof:
    type: checkbox_field
    category: ninja_qualifications
    subcategory: skill_attestations
    source_type: honor_declaration
    required_for: []
    optional_for: [services]
    defense_required: true
  dragon_taming_permit:
    type: document_upload
    category: unicorn_identity
    subcategory: special_permits
    source_type: authentic_source
    required_for: []
    optional_for: [supplies, works]
    defense_optional: true
  time_travel_authorization:
    type: checkbox_field
    category: rocket_certifications
    subcategory: special_authorizations
    source_type: authentic_source
    required_for: []
    optional_for: [services]
    defense_optional: true

test:
  <<: *development

sandbox: 
  <<: *development

production: 
  <<: *development