# Field Categories Configuration
# Defines display categories for form fields

development: &development
  unicorn_identity: "Identité de la licorne (test)"
  pizza_exclusions: "Motifs d'exclusion liés aux pizzas (démo)"
  coffee_compliance: "Conformité café et croissants (fictif)"
  rocket_certifications: "Certifications fusées spatiales (exemple)"
  ninja_qualifications: "Qualifications ninja professionnelles (test)"

test:
  <<: *development

sandbox: 
  <<: *development

production: 
  <<: *development