# Field Requirements Configuration
# Defines which fields are required or optional for different market types and defense contexts

default: &default
  # Market Type Requirements
  market_types:
    supplies:
      required:
        - siret
        - main_activity
        - company_name
        - manager_name
        - postal_address
        - headquarters_address
        - email
        - phone_number
        - criminal_conviction
        - equality_violation
        - labor_law_violation
        - negotiation_obligation_breach
        - judicial_liquidation
        - personal_bankruptcy
        - tax_payment_declaration
        - legal_obligations_compliance
        - social_contributions_compliance
        - disabled_workers_employment
        - foreign_workers_list
      optional:
        - prior_contract_breach
        - undue_influence
        - collusion_presumption
        - conflict_of_interest
        - greenhouse_gas_report
        - vigilance_plan
        - annual_turnover
        - sector_turnover
        - financial_statements
        - professional_risk_insurance
        - average_annual_workforce
        - team_presentation
        - qualibat_certificate
        - qualifelec_certificate
        - rge_certificate
        - opqibi_certificate
        - bio_certification
        - ess_certification
        - main_deliveries_three_years
        - delivery_attestations_three_years
        - technical_equipment_description
        - quality_measures_description
        - samples_photos_descriptions
        - supply_chain_management
        - environmental_management_measures
        - complex_products_control

    services:
      required:
        - siret
        - main_activity
        - company_name
        - manager_name
        - postal_address
        - headquarters_address
        - email
        - phone_number
        - criminal_conviction
        - equality_violation
        - labor_law_violation
        - negotiation_obligation_breach
        - judicial_liquidation
        - personal_bankruptcy
        - tax_payment_declaration
        - legal_obligations_compliance
        - social_contributions_compliance
        - disabled_workers_employment
        - foreign_workers_list
      optional:
        - prior_contract_breach
        - undue_influence
        - collusion_presumption
        - conflict_of_interest
        - greenhouse_gas_report
        - vigilance_plan
        - annual_turnover
        - sector_turnover
        - financial_statements
        - professional_risk_insurance
        - average_annual_workforce
        - team_presentation
        - qualibat_certificate
        - qualifelec_certificate
        - rge_certificate
        - opqibi_certificate
        - bio_certification
        - ess_certification
        - qualiopi_certificate
        - main_deliveries_three_years
        - delivery_attestations_three_years
        - technical_equipment_description
        - quality_measures_description
        - samples_photos_descriptions
        - supply_chain_management
        - environmental_management_measures
        - complex_products_control

    works:
      required:
        - siret
        - main_activity
        - company_name
        - manager_name
        - postal_address
        - headquarters_address
        - email
        - phone_number
        - criminal_conviction
        - equality_violation
        - labor_law_violation
        - negotiation_obligation_breach
        - judicial_liquidation
        - personal_bankruptcy
        - tax_payment_declaration
        - legal_obligations_compliance
        - social_contributions_compliance
        - disabled_workers_employment
        - foreign_workers_list
      optional:
        - prior_contract_breach
        - undue_influence
        - collusion_presumption
        - conflict_of_interest
        - greenhouse_gas_report
        - vigilance_plan
        - annual_turnover
        - sector_turnover
        - financial_statements
        - professional_risk_insurance
        - average_annual_workforce
        - team_presentation
        - qualibat_certificate
        - qualifelec_certificate
        - rge_certificate
        - opqibi_certificate
        - cqp_tp_certificate
        - cibtp_cnetp_certificate
        - pro_btp_certificate
        - main_works_five_years
        - works_attestations_five_years
        - technical_equipment_description
        - quality_measures_description
        - samples_photos_descriptions
        - supply_chain_management
        - environmental_management_measures

  # Defense Industry Requirements
  defense:
    required:
      - defense_supply_chain
    optional:
      - company_category
      - prior_contract_breach
      - undue_influence
      - collusion_presumption
      - conflict_of_interest
      - greenhouse_gas_report
      - vigilance_plan
      - annual_turnover
      - sector_turnover
      - financial_statements
      - professional_risk_insurance
      - average_annual_workforce
      - team_presentation
      - qualibat_certificate
      - qualifelec_certificate
      - rge_certificate
      - opqibi_certificate
      - bio_certification
      - ess_certification
      - qualiopi_certificate
      - cqp_tp_certificate
      - cibtp_cnetp_certificate
      - pro_btp_certificate
      - main_deliveries_three_years
      - delivery_attestations_three_years
      - main_works_five_years
      - works_attestations_five_years
      - technical_equipment_description
      - quality_measures_description
      - samples_photos_descriptions
      - supply_chain_management
      - environmental_management_measures
      - complex_products_control

development:
  <<: *default

test:
  <<: *default

sandbox:
  <<: *default

production: 
  <<: *default