# Field Requirements Configuration
# Defines required and optional fields for market types and defense industry

development: &development
  market_type_requirements:
    supplies:
      required_fields:
        - unicorn_birth_certificate
        - pizza_allergy_declaration
        - coffee_addiction_level
      available_optional_fields:
        - rocket_piloting_license
        - ninja_stealth_certificate
        - dragon_taming_permit
    services:
      required_fields:
        - unicorn_horn_measurement
        - pineapple_pizza_stance
      available_optional_fields:
        - moon_landing_experience
        - invisible_skill_proof
        - time_travel_authorization
    works:
      required_fields:
        - unicorn_birth_certificate
        - croissant_eating_frequency
        - ninja_stealth_certificate
      available_optional_fields:
        - rocket_piloting_license
        - coffee_addiction_level
        - dragon_taming_permit

  defense_requirements:
    required_fields:
      - ninja_stealth_certificate
      - invisible_skill_proof
    available_optional_fields:
      - time_travel_authorization
      - dragon_taming_permit

test:
  <<: *development

sandbox: 
  <<: *development

production: 
  <<: *development