# Source Types Configuration
# Defines data source types with labels and badge styles

development: &development
  authentic_source:
    label: "De source authentique"
    badge_class: "fr-badge--success"
  honor_declaration:
    label: "Déclaré sur l'honneur"
    badge_class: "fr-badge--info"

test:
  <<: *development

sandbox: 
  <<: *development

production: 
  <<: *development