default: &default
  adapter: postgresql
  encoding: unicode
  username: voie_rapide
  password: wow*veryrapide
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 15 } %>

development:
  <<: *default
  host: <%= ENV.fetch("POSTGRES_HOST") { 'localhost' } %>
  database: voie_rapide_development

test: &test
  <<: *default
  host: localhost
  database: voie_rapide_test

production: *test
